framework:
  github: aplus-framework/app
  version: 23.3
  website: aplus-framework.com/packages/app

  bootstrap:
    - mkdir -p storage/logs
    - chown -R www-data:www-data storage/logs
  deps:
    - libsodium
    
  modules:
    - sodium
